ministryofjustice/opg-data-casrec-migration

README.md
docker-compose.yml

Instructions and docker stuff so we can access sirius db locally

Make Sirius DB run locally

---

casrec_db/Dockerfile
casrec_db/setup/create_casrec_db_tables.py
docker-compose.yml

Get the sample data into a pg database

First pass at getting sample data into pg database

---

.circleci/config.yml
etl1/casrec_load.py
terraform/cloud9.tf
terraform/database.tf

The purpose of this PR is to sort out some bugs in the pre deployment, create a cloud9 instance and make the dev pipeline only do a plan.
Next I wish to make the dev pipeline do something clever based on the terraform but too much for this PR.
Nothing special to see here. Want to eventually have a temporary spun up cloud 9 but for now a shared one will do.
Still not quite loaded all pre data but at least we can make a start with what is loaded.

IN-397 handle mixed case file names

---

.gitignore
etl3/sql/sirius_id_cols.sql

IN-368 fix git ignore

---

.circleci/config.yml
README.md
base_image/Dockerfile
base_image/requirements.txt
docker-compose.override.yml
migrate.sh
migration_steps/acquire_target_ids/Dockerfile
migration_steps/acquire_target_ids/requirements.txt
migration_steps/load_casrec/Dockerfile
migration_steps/load_casrec/requirements.txt
migration_steps/load_s3/Dockerfile
migration_steps/load_s3/requirements.txt
migration_steps/load_to_target/Dockerfile
migration_steps/load_to_target/requirements.txt
migration_steps/transform_casrec/Dockerfile
migration_steps/transform_casrec/requirements.txt

Speed up the build.. unfortunately the push process can't easily be parallelised so we don't save as much time as I'd hoped but still:
Old:
New:
So bit quicker anyway...
I guess more importantly all the containers have volume mounts so we can edit in real time.
Used overrides for volume mounts and made a base image for the docker builds.

IN-484 speed up builds and make docker use volumes

---

.circleci/config.yml
migration_steps/transform_casrec/requirements.txt
migration_steps/transform_casrec/tests/requirements.txt

IN-485 add unit tests

---

.circleci/config.yml
docker-compose.override.ci.yml
docs/ci_scripts/assume_sirius_dev.sh
docs/ci_scripts/cancel_builds.py
docs/ci_scripts/login_code_artifact.sh
docs/ci_scripts/requirements.txt
migrate.sh
migration_steps/load_casrec/casrec_load.py
terraform/ecs.tf
terraform/sirius_tasks.toml
terraform/template.tf

Add main build to the pipeline, add cancel build, add extra case fixtures for sirius
Used the sirius fixtures for the fixtures, used our codeartifact shared code for cancel redundant builds. Pulling in from AWS S3 and using docker override file for the local full run in pipeline.

In 494 - Add main build to the pipeline, add cancel build, add extra case fixtures for sirius

---

.circleci/config.yml
docker-compose.override.ci.yml
docs/ci_scripts/assume_sirius_dev.sh
docs/ci_scripts/cancel_builds.py
docs/ci_scripts/login_code_artifact.sh
docs/ci_scripts/requirements.txt
migrate.sh
migration_steps/load_casrec/casrec_load.py
terraform/ecs.tf

IN-486b lets see if we can get build running in pipeline

---

README.md
import_mapping_definitions.py

Helper script for pulling in versions
Can be run multiple times and keeps your original version whilst pulling in the new version and extracting it to the correct folder.
NA

IN-504 add helper script in this repo

---

migration_steps/transform_casrec/app/app.py
migration_steps/transform_casrec/app/data_tests/test_all_fields_tested.py
migration_steps/transform_casrec/app/data_tests/test_calculated_values.py
migration_steps/transform_casrec/app/data_tests/test_complex_joins.py
migration_steps/transform_casrec/app/data_tests/test_default_values.py
migration_steps/transform_casrec/app/data_tests/test_lookup_tables.py
migration_steps/transform_casrec/app/data_tests/test_simple_joins.py
migration_steps/transform_casrec/app/data_tests/test_simple_transformations.py
migration_steps/transform_casrec/app/data_tests/test_transformations_convert_to_bool.py
migration_steps/transform_casrec/app/data_tests/test_transformations_squash_columns.py
migration_steps/transform_casrec/app/run_data_tests.py

Replaced the `print` statements with proper logs, and made the levels match the levels in the app

IN-522 data tests logging

---

README.md
casrec_data/README.md
casrec_data/do_anonymising/anon_csv_data.py
docs/support_scripts/generate_casrec_schema/README.md
docs/support_scripts/generate_casrec_schema/create_tables.py
docs/support_scripts/generate_casrec_schema/datatypes.py
docs/support_scripts/generate_casrec_schema/generate_file_per_table.py
docs/support_scripts/generate_casrec_schema/get_relationships.py
docs/support_scripts/mapping_doc_to_json/mapping_all_sheets.py
migration_steps/integration/prepare_target/app/app.py
migration_steps/integration/schema_setup/app/app.py
migration_steps/load_casrec/app/app.py
migration_steps/load_s3/load_s3_local.py
migration_steps/load_to_target/app/entities/client.py
migration_steps/load_to_target/app/load_to_target_helpers.py
migration_steps/shared/config2.py
migration_steps/shared/helpers.py
migration_steps/transform_casrec/app/data_tests/test_all_fields_tested.py
migration_steps/transform_casrec/app/data_tests/test_row_counts.py
migration_steps/transform_casrec/app/data_tests/test_simple_joins.py
migration_steps/transform_casrec/app/transform_data/conditional_lookups.py
migration_steps/transform_casrec/app/utilities/standard_transformations.py
migration_steps/transform_casrec/transform_tests/transform_data/calculations/cases_calculations_called.py
migration_steps/transform_casrec/transform_tests/utilities/convert_json_to_mappings/test_get_mappings.py
migration_steps/transform_casrec/transform_tests/utilities/standard_transformations/convert_to_bool/test_convert_to_bool.py
migration_steps/transform_casrec/transform_tests/utilities/standard_transformations/squash_columns/test_squash_columns.py

Bunch of linting changes recommended by precommit
Pre-commit script added to readme

Commit to precommit

---

README.md
docker-compose.ci.yml
docker-compose.override.yml
docker-compose.sirius.yml
docker-compose.yml
migrate.sh
migrate_to_sirius.sh
migration_steps/validation-dockerfile
migration_steps/validation/requirements.txt
migration_steps/validation/validate.sh
migration_steps/validation/validate_db/app/app.py
terraform/ecr.tf
terraform/ecs_etl5.tf
terraform/state_machine.tf

This ticket is just to get the step in and have it build against ECS/etl5

IN-540 add validation step to ECS (just a placeholder script)

---

terraform/behat_migration.tf

Fix hard coded behat test
Pulled from the app container data object.

IN-583 make arn for behat image dynamic

---

terraform/behat_migration.tf

IN-489b fix pipeline since rebuild

---

.circleci/config.yml
migration_steps/integration/merge_with_target/app/merge_helpers.py
terraform/sirius_tasks.toml

Sirius doesn't seem to use ingest users any more. Checked and others still exist.

IN-594 fix ingest

---

docker-compose.override.yml
migration_steps/load_casrec/app/app.py
migration_steps/validation-dockerfile
migration_steps/validation/post_migration_db_tasks/app/app.py
migration_steps/validation/validate.sh

Chuck in a reindex and update stats... i'm guessing this may or may not work well in preprod and we may have to revisit how it does this. We shall see...
Just a couple of sql commands (might need to use a cursor and do indiv tables if this doesn't work in preprod)
autocommit needs to be off

IN-618 reindex and update stats on sirius

---

terraform/terraform.tfvars.json

lets try this new preprod data

---

migration_steps/load_casrec/app/app.py

Add incrementing rows to the casrec tables that handles multi file input
Was really really dumb. Spent ages mucking around with dataframes and then remembered i could just at an identity col... sad face
Think more before writing code...

IN-640 add row count to records

---

.circleci/config.yml

circle fix for bad dependency

---

migration_steps/integration/business_rules/app/app.py
migration_steps/integration/integration.sh
migration_steps/integration/reindex_ids/app/app.py
migration_steps/integration/reindex_ids/app/reindex/move_by_table.py

Had this option `server_side_cursors` turned on in `apply_business_rules` for some reason I can't remember and removing that fixed one of the broken things.
The other bit was that the integration schema wasn't working as expected so I removed the `schema_setup` bit and just added a super basic `CREATE SCHEMA` bit into `reindex_ids` - it just needs to be an empty schema anyway so it doesn't actually matter.

Pipeline broke

---

migrate.sh
migration_steps/integration/load_to_staging/app/move.py
migration_steps/integration/load_to_staging/app/setup.py
migration_steps/integration/reindex_ids/app/reindex/move_by_table.py
migration_steps/integration/reindex_ids/app/reindex/reindex_foreign_keys.py
migration_steps/integration/reindex_ids/app/reindex/reindex_primary_keys.py
migration_steps/load_to_sirius/app/app.py
migration_steps/load_to_sirius/app/move.py
migration_steps/load_to_sirius/app/reset_sequences.py
migration_steps/shared/db_helpers.py
migration_steps/shared/tables.json
migration_steps/transform_casrec/app/utilities/db_insert.py

So `caseitem_note` was failing in `load_to_sirius` and it wasn't telling anyone. I've added a load of these: `sys.exit(1)` to make the whole thing fail when there's a problem.
Also added an `order_by` to the `tables.json` so I can make the chunking work properly. This was what was actually making it fail - you gotta order by something consistent or you get duplicates, which is what was happening here.

IN-643_caseitem_note_fix

---

migration_steps/transform_casrec/app/entities/deputies/phonenumbers_daytime.py
migration_steps/transform_casrec/app/entities/deputies/phonenumbers_evening.py

Because in my infinite wisdom I was joining on email address????
Changed to deputy number now, recreated locally and it doesn't fail so 🤞

IN-645 deputy phone numbers break in preprod

---

migration_steps/transform_casrec/app/entities/deputies/order_deputy.py

Preprod-lems

---

migration_steps/transform_casrec/app/entities/deputies/order_deputy.py

Fix problem where deputies are associated with one order

---

migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

IN-652-Deputies-Validation

---

migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

Just a rebase of a humble ticket that's been waiting its turn for weeks

IN-649 Supervision Log LevelDB Valiation

---

migration_steps/transform_casrec/transform/app/entities/deputies/order_deputy.py

don't include rows with null order_id or deputy_id

IN-690 unlinked deputies

---

.circleci/config.yml

missed the branch change when reverting the pipeline to the real setup after testing

missed the branch change in kick off job

---

docs/ci_scripts/run_step_function.py

Another thing missed when running the pipe without full step func run...

make step runner handle two step functions properly

---

docs/ci_scripts/run_step_function.py

Another bug that is now important that i missed previously...

fix wait for

---

.circleci/config.yml
.circleci/config_hack_pre.yml
.circleci/config_hack_qa.yml

upgrade to tf 14.11

---

migration_steps/prepare/prepare_target/app/sql/rollback_fixtures.template.sql
migration_steps/shared/config.py
migration_steps/shared/db_helpers.py
migration_steps/shared/mapping_definitions/client_violent_warnings_mapping.json
migration_steps/shared/mapping_definitions/deputy_violent_warnings_mapping.json
migration_steps/shared/mapping_definitions/lookups/warning_violent_lookup.json
migration_steps/shared/mapping_definitions/summary/mapping_progress_summary.json
migration_steps/shared/progress/transform_progress.json
migration_steps/transform_casrec/transform/app/entities/death/__init__.py
migration_steps/transform_casrec/transform/app/entities/death/client_death_notifications.py
migration_steps/transform_casrec/transform/app/entities/death/deputy_death_notifications.py
migration_steps/transform_casrec/transform/app/entities/warnings/__init__.py
migration_steps/transform_casrec/transform/app/entities/warnings/client_person_warning.py
migration_steps/transform_casrec/transform/app/entities/warnings/client_violent_warnings.py
migration_steps/transform_casrec/transform/app/entities/warnings/deputy_person_warning.py
migration_steps/transform_casrec/transform/app/entities/warnings/deputy_violent_warnings.py
migration_steps/transform_casrec/transform/app/transform_data/apply_datatypes.py
migration_steps/transform_casrec/transform/app/transform_data/conditional_lookups.py
migration_steps/transform_casrec/transform/app/transform_data/simple_mappings.py
migration_steps/transform_casrec/transform/app/transform_data/transform.py
migration_steps/transform_casrec/transform/app/utilities/basic_data_table.py
migration_steps/transform_casrec/transform/app/utilities/custom_errors.py
migration_steps/transform_casrec/transform/app/utilities/db_insert.py
migration_steps/transform_casrec/transform/app/utilities/remove_empty_rows.py

First pass at `warnings` - violent only so far

In 462 warnings

---

.github/workflows/scanner.yml

Add in action to scan the repo packages on a cron

add in scanner report

---

migrate.sh
migration_steps/prepare/create_stage_schema/app/app.py
migration_steps/prepare/prepare_target/app/app.py
migration_steps/shared/db_helpers.py
migration_steps/shared/mapping_definitions/client_death_notifications_mapping.json
migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

Update DBValidation in the light of some of the mapped columns which have been enabled recently
Other small semantic/logging updates

In dbv updated mappings

---

migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

In 461 deathvalidation

---

migration_steps/shared/mapping_definitions/client_nodebtchase_warnings_mapping.json
migration_steps/shared/mapping_definitions/client_saarcheck_warnings_mapping.json
migration_steps/shared/mapping_definitions/client_special_warnings_mapping.json
migration_steps/shared/mapping_definitions/client_violent_warnings_mapping.json
migration_steps/shared/mapping_definitions/deputy_special_warnings_mapping.json
migration_steps/shared/mapping_definitions/deputy_violent_warnings_mapping.json
migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

Retrofit DB validation to  warnings entities

In 726 warnings db validation

---

docs/ci_scripts/get_image.py

Now that we have lots of images we have ventured into the realm of pagination and the script is bringing back wrong deploy.
Fix script so that it uses nextToken to paginate through all pages and find the latest tag.
Loop and use nextToken

IN-769 fix pagination on get tags script

---

migration_steps/shared/mapping_definitions/client_addresses_mapping.json
migration_steps/shared/mapping_definitions/client_death_notifications_mapping.json
migration_steps/shared/mapping_definitions/client_nodebtchase_warnings_mapping.json
migration_steps/shared/mapping_definitions/client_persons_mapping.json
migration_steps/shared/mapping_definitions/client_saarcheck_warnings_mapping.json
migration_steps/shared/mapping_definitions/client_special_warnings_mapping.json
migration_steps/shared/mapping_definitions/client_violent_warnings_mapping.json
migration_steps/shared/mapping_definitions/deputy_persons_mapping.json
migration_steps/shared/mapping_definitions/deputy_special_warnings_mapping.json
migration_steps/shared/mapping_definitions/deputy_violent_warnings_mapping.json
migration_steps/shared/mapping_definitions/lookups/title_codes_lookup.json
migration_steps/shared/mapping_definitions/summary/mapping_progress_summary.json
migration_steps/transform_casrec/transform/app/entities/warnings/client_person_warning.py
migration_steps/transform_casrec/transform/app/transform_data/apply_datatypes.py

This one's little brother:
https://github.com/ministryofjustice/opg-data-casrec-migration-mappings/pull/48

IN-174 mapping repo update

---

.circleci/config.yml
.circleci/config_hack_pre.yml
.circleci/config_hack_qa.yml
aws_config
docs/ci_scripts/assume_sirius_dev.sh
docs/ci_scripts/login_code_artifact.sh
docs/supporting_documents/circleci-pre/config.yml
migration_steps/load_casrec/app/app.py
migration_steps/shared/helpers.py
terraform/casrec_migration_tasks.toml
terraform/provider.tf
terraform/sirius_tasks.toml
terraform/variables.tf

User seems to have been replaced in org infra. Lets fix it here too.

replace integrations-ci with migrations-ci

---

migration_steps/shared/mapping_definitions/summary/mapping_progress_summary.json
migration_steps/shared/mapping_definitions/tables/table_definitions.json
migration_steps/shared/tables.json
migration_steps/transform_casrec/transform/app/entities/visits/visits.py

IN-796 link visits to clients

---

.gitignore
migration_steps/validation/api_tests/app.py

The existing smoke user doesn't have the right oomf to run against al the APIs. This is easiest way to fix.

users gonna need a bit more privs

---

scripts/ci_scripts/run_jenkins_job.sh

You iiidiot shtimpy! Left in the flag I was testing with so that i didn't have to do full restores :(.

switch out restore flag

---

migration_steps/shared/config.py

remove preprod (temp fix)

---

migration_steps/load_to_sirius/move_data/update_data.py
migration_steps/load_to_sirius/move_data/utilities.py

Swapped out using `mogrify` to format the update queries to using a custom generator like in other places.
Speeded through so Jim can test on preprod.
Future ticket to be added to remove the `mogrify` method so we don't fall into its trap again...

IN-810_change_update_query_generation

---

migration_steps/shared/validation_mapping.json

...we're not migrating this field or altering Sirius' value

Remove createddate from validation 

---

.circleci/config.yml
scripts/ci_scripts/extend_casmigrate_ttl.py
scripts/ci_scripts/run_jenkins_job.sh

Rebuild the casmigrate environment
Rebuild the env.
Run a script that updates the TTL for dynamo.
Dynamo

IN-856 rebuild casmigrate

---

migration_steps/load_to_sirius/move_data/update_data.py
migration_steps/validation/validate_db/app/app.py

So the updates had half the chunking - the half that did 2000 rows then stopped 
Now it will update all the records!

IN-845 update more than one chunk

---

migration_steps/load_casrec/app/app.py

Source data structure is not always in exactly the same format, had an error where the second part of a multipart load had different columns.
This will add any extra cols if required, so won't crash out at the start.

IN-877 add in extra columns to source database 

---

migration_steps/prepare/case_details_to_s3/app/app.py
migration_steps/shared/config.py
migration_steps/transform_casrec/filter_data/app/app.py
migration_steps/transform_casrec/transform/app/app.py
migration_steps/transform_casrec/transform/app/entities/invoice/__init__.py
migration_steps/transform_casrec/transform/app/entities/invoice/finance_invoice_ad.py
migration_steps/transform_casrec/transform/app/transform_data/apply_conditions.py
migration_steps/transform_casrec/transform/app/transform_data/simple_transformations.py
migration_steps/transform_casrec/transform/app/utilities/standard_transformations.py
migration_steps/transform_casrec/transform/transform_tests/utilities_tests/standard_transformations/add_one_year/test_add_one_year.py
migration_steps/transform_casrec/transform/transform_tests/utilities_tests/standard_transformations/first_two_chars/test_first_two_chars.py
migration_steps/transform_casrec/transform/transform_tests/utilities_tests/standard_transformations/multiply_by_100/test_multiply_by_100.py
migration_steps/validation/api_tests/shared/api_test.py
migration_steps/validation/validate_db/app/app.py
scripts/api_tests_generator/app.py
scripts/archived_scripts/test_client_api_request.py
scripts/case_details_to_s3/case_details_to_s3.py
scripts/casrec_data/do_anonymising/anon_csv_data.py
scripts/ci_scripts/run_step_function.py
scripts/ecs_task_runner/run_ecs_task.py

Filter out any non-AD invoices and create the following transformations:
- extract invoice type - first two characters of invoice reference
- set endDate to 1 year from raisedDate
- convert invoice amount to an integer
A bunch of other files got reformatted from running pre-commit
Add a condition to filter out non-AD invoices
Add simple transformations

Conditions and transformations for AD invoices

---

migration_steps/integration/integration.sh
migration_steps/load_to_sirius/load_to_sirius.sh
migration_steps/prepare/prepare.sh
migration_steps/validation/validate.sh

Allows migration steps to run once promoted to PreQA
Simply add env name to list of permitted emvironments

Enable steps to run on new preqa env

---

terraform/ecs.tf
terraform/parameter_store.tf

IN-875 - Add Parameters for Lay Team

---

migration_steps/integration/business_rules/app/app.py
migration_steps/integration/load_to_staging/app/app.py
migration_steps/integration/reindex_ids/app/app.py
migration_steps/shared/config.py
migration_steps/transform_casrec/filter_data/app/app.py
migration_steps/transform_casrec/filter_data/app/sql/delete_filtered_source_data.template.sql
migration_steps/transform_casrec/transform/app/app.py

We've moved team filter to a parameter store value which Andy helped set up.
Team filter is specified in either param store (in CI) or in console prompt (dev) - the code that reconciles this has been moved to central shared function and the other steps updated to use this function

Bau teamfiltering

---

.circleci/config.yml
migration_steps/shared/config.py
migration_steps/validation/api_tests/response_tests/app.py
migration_steps/validation/validate_db/app/app.py
terraform/parameter_store.tf

Temporarily disable visits so we can get a clean build which is releasable right through to QA

Bau disablevisits

---

scripts/ci_scripts/get_environment_entities.py

Add preqa env to accounts list

---

migration_steps/transform_casrec/filter_data/app/sql/delete_filtered_source_data.template.sql

The filtering stuffs been waiting for testing for so long that we've had some new entities in the meantime
Apply filtering to those entities

Filter newer entities Crec, Visits, remarks

---

.circleci/config.yml
migrate_tagged_version.sh

Few minor issues. There was some contention between jobs running at the same time. Also wanted to make the TTL protection affect dev job even where job failed.
NA

IN-904 some minor stability improvements

---

.circleci/config.yml
migration_steps/prepare/prepare.sh
migration_steps/transform_casrec/transform/app/transform_data/apply_conditions.py

Timings were likely mucked up as RDS for casrec side may have fallen asleep so all processes ended up trying to pull from it at the same time. Move delete script around to remedy this.

fix timings

---

migration_steps/transform_casrec/transform/app/transform_data/default_columns.py
migration_steps/transform_casrec/transform/app/utilities/convert_json_to_mappings.py

notes description

---

migration_steps/validation/api_test_data_s3_upload/app/validation/csvs/invoice.csv
migration_steps/validation/api_tests/functional_tests/app.py
migration_steps/validation/api_tests/response_tests/app.py
migration_steps/validation/api_tests/shared/api_test.py
scripts/api_tests_generator/app.py
scripts/api_tests_generator/examples/invoices.json
scripts/api_tests_generator/invoices.csv

Scaffolding for response tests and functional tests for invoices
Just testing write off and credit functionality here. Will do the trickier tests when the individual credits have been migrated as part of that entity.

IN-885 scaffolding for response tests and functional tests for invoices

---

migration_steps/validation/api_tests/shared/api_test.py

Add crec tests to PreProd
Find correct data to check:
- Create csv
- Load it into S3
- Update the entries in this repo so it runs (that's the file change din here)

IN-739 crec api test

---

migration_steps/integration/load_to_staging/app/setup.py
migration_steps/transform_casrec/transform/app/entities/bonds/bonds_active.py
migration_steps/transform_casrec/transform/app/entities/bonds/bonds_dispensed.py
migration_steps/transform_casrec/transform/app/entities/cases/cases.py
migration_steps/transform_casrec/transform/app/entities/clients/addresses.py
migration_steps/transform_casrec/transform/app/entities/clients/persons.py
migration_steps/transform_casrec/transform/app/entities/clients/phonenumbers.py
migration_steps/transform_casrec/transform/app/entities/crec/persons.py
migration_steps/transform_casrec/transform/app/entities/death/client_death_notifications.py
migration_steps/transform_casrec/transform/app/entities/death/deputy_death_notifications.py
migration_steps/transform_casrec/transform/app/entities/deputies/addresses.py
migration_steps/transform_casrec/transform/app/entities/deputies/persons.py
migration_steps/transform_casrec/transform/app/entities/deputies/phonenumbers_daytime.py
migration_steps/transform_casrec/transform/app/entities/deputies/phonenumbers_evening.py
migration_steps/transform_casrec/transform/app/entities/invoice/finance_invoice.py
migration_steps/transform_casrec/transform/app/entities/remarks/notes.py
migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_lodging_details.py
migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_logs.py
migration_steps/transform_casrec/transform/app/entities/supervision_level/supervision_level_log.py
migration_steps/transform_casrec/transform/app/entities/visits/visits.py

Ensure chunking is not interrupted by a EmptyDataFrame exception during conditions/filtering

Fix chunking in all entities

---

migration_steps/load_casrec/app/app.py

When loading data in from an xlsx file, dates get converted to a datetime object, while empty date cells are converted to "NaT".
This PR ensures that pat.DOB field is converted back to a date string, and any "NaT"s are converted to empty strings.
Convert DOB datetime to date and NaT to empty string.

IN-912 Fix client_persons validation errors

---

migration_steps/load_casrec/app/app.py

BAU fix four columns in cases NaT and timestamps

---

migration_steps/load_casrec/app/app.py

Fix deputy_death_notification and deputy_person validation errors
Convert deputy."Disch Death" datetime to date when imported from xlsx

IN-915 convert deputy."Disch Death" datetime to date when imported from xlsx

---

.circleci/config.yml

put workflow back

---

migration_steps/shared/validation_mapping.json

IN-1007 Set correct default client note description

---

migration_steps/shared/validation_mapping.json
migration_steps/transform_casrec/transform/app/transform_data/simple_transformations.py
migration_steps/transform_casrec/transform/app/utilities/standard_transformations.py
migration_steps/transform_casrec/transform/transform_tests/utilities_tests/standard_transformations/is_at_least_one_set/test_is_at_least_one_set.py
migration_steps/validation/validate_db/app/app.py
migration_steps/validation/validate_db/app/sql/fixed_sql/annual_report_lodging_details.sql

[IN-748](https://opgtransform.atlassian.net/browse/IN-748)
Add a new transform to set a column to TRUE if at least one of a set of columns contains a (non-null, non-empty) value.
Add basic validation SQL for annual_report_lodging_details table.
n/a

IN-748 Annual report lodging details

---

migration_steps/prepare/delete_existing_data/sql/delete_statements.sql

Deletion broke over the weekend due to some new data in real sirius.
The ordering was off. Supervision notes needs to be before annual reports.
NA

correct ordering issue in delete statements

---

migration_steps/load_to_sirius/post_migration_db_tasks/finance_batch_numbers.py

Migrated clients do not appear in the New Cases report
Set a batch number in finance_person for all migrated clients.

IN-1001 Migrated clients should not appear in the New Cases report

---

.pre-commit-config.yaml
.secrets.baseline

Update precommit hooks
Just updated them but flake8 has it's own repo so used that instead of using as part of precommit repo as it no longer exists as part of that repo
NA

update precommit hooks

---

migration_steps/shared/sql/transformation_functions.sql

Fix convert_to_timestamp validation function
Cast dates to date and times to time, then back to varchars

IN-999 Fix convert_to_timestamp validation function

---

.circleci/config.yml

Flag was missed on pre nightly run

update load_casrec flag

---

migration_steps/prepare/create_skeleton_data/app/skeleton_data.py
migration_steps/shared/tables.json
migration_steps/validation/api_tests/functional_tests/app.py
migration_steps/validation/api_tests/shared/api_test.py

Fix 500 code errors when creating new entities in Sirius
Ensure that sequences get reset for all migrated entities.
Re-enable client, death and invoice functional tests.

IN-1021 Add missing sequence definitions and re-enable functional tests

---

.circleci/config.yml

extend api test timeout

---

migration_steps/shared/sql/drop_transformation_functions.sql
migration_steps/shared/sql/transformation_functions.sql
migration_steps/shared/validation_mapping.json
migration_steps/transform_casrec/transform/app/utilities/standard_transformations.py
migration_steps/validation/validate_db/app/app.py

IN-941
Add validations for finance_remissions and finance_exemptions to validation_mapping.json

IN-941 Add DB validations for Fee Reductions

---

migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

IN-1054
Standard DB validation for deputy_addresses

IN-1054 DB validation for deputy_addresses

---

terraform/environment/sirius_variables.tf

This infra has now been removed.

remove old elastic vars as not used

---

migration_steps/prepare_source_data/filter_data/app/app.py
migration_steps/validation/api_tests/shared/api_test.py

Remove filtered cases from api tests so that they don't break when we do filtering
Take list of filtered cases and hold them as a list. Check each case isn't in the list.
NA

IN-1063 filter out filtered cases from api tests

---

.circleci/config.yml

New version on tf fixes some bugs: https://github.com/hashicorp/terraform/releases/tag/v1.1.2
Also we had issue seeing profile in modified circle jobs
upgrade tf and put in env var for aws config
NA

upgrade terraform and fix profile issue

---

migration_steps/validation/validate_db/app/sql/fixed_sql/timeline_event.sql

[IN-1084](https://opgtransform.atlassian.net/browse/IN-1084)
See ticket
n/a

IN-1084 Fix static validation SQL for timeline_event

---

migration_steps/shared/validation_mapping.json

Fix DB validation
Revert recent changes that broke the validation.
Created test cases in the anon dataset as described on the ticket

IN-1086 Fix DB validation for client_addresses

---

migration_steps/prepare_source_data/prepare_source_data.sh

Ensure that we're not loading fixtures in real-data environments
Add a conditional in the shell script

Do not load Casrec fixtures in real-data environments

---

.circleci/config.yml

test some circle config

---

.circleci/config.yml

Had spurious task left in overnight config

modify circle config

---

migration_steps/shared/validation_mapping.json
migration_steps/validation/validate_db/app/app.py

IN-944
Standard DB validation for Finance Order

IN-944 Finance Order DB validation

---

migration_steps/shared/validation_mapping.json

Fix Finance Order DB validation
Convert empty strings to NULL before casting to date

IN-944 Fix failing DB validation

---

terraform/shared/terraform.tfvars.json

Change the folder for our data.

add new source folder

---

migration_steps/transform_casrec/transform/app/entities/tasks/tasks.py

[IN-1098](https://opgtransform.atlassian.net/browse/IN-1098)
Exclude tasks with a case no. which does not appear in the Sirius cases table.
n/a

IN-1098 Only migrate tasks whose case no. is in cases table

---

migration_steps/shared/tables.json

[IN-1107](https://opgtransform.atlassian.net/browse/IN-1107)
Add missing sequence for annual_report_type_assignments. 
n/a

IN-1107 Add sequence for annual_report_type_assignments ID

---

docker-compose.sirius.yml
migrate.sh
migration_steps/load_casrec/app/app.py
migration_steps/load_casrec_fixtures-dockerfile
migration_steps/shared/db_helpers.py
terraform/shared/state_machine.tf

Load casrec step occasionally had issues and it's design looked very flakey so did a slight redesign and refactor.
Before we had a number of processes that didn't have any self awareness trying to coordinate based on a progress table and another table list table. Now each process is aware of it's own process number and how many other processes there are and it coordinates around process 1 setting things up and the other processes joining in on the processing.
NA

IN-1077 sanitise load casrec

---

migration_steps/shared/validation_mapping.json

[IN-1109](https://opgtransform.atlassian.net/browse/IN-1109)
Validation SQL must mirror what happens in the transform.
n/a

IN-1109 Fix validation SQL for tasks

---

migration_steps/load_casrec/app/app.py
terraform/shared/terraform.tfvars.json

update s3 folder and fix load script

---

migrate.sh
migration_steps/prepare_source_data/prepare_source_data.sh

The Corref filter wasn't being passed corref params through from console
* [x ] I have performed a self-review of my own code

IN-1128 fix pass corref params to filter in local migrate.sh

---

.circleci/config.yml
README.md
docs/supporting_documents/circleci-pre/config.yml
migrate_tagged_version.sh
reset_local_env.sh
scripts/ci_scripts/get_image.py

switch branch to master to main

---

.circleci/config.yml
README.md
docs/supporting_documents/circleci-pre/config.yml
migrate_tagged_version.sh
reset_local_env.sh
scripts/ci_scripts/get_image.py

switch branch to main from master

---

.circleci/config.yml
migration_steps/validation/api_tests/functional_tests/app.py
migration_steps/validation/api_tests/response_tests/app.py

We don't want to exit the pipeline any more for API test fails as we are going to be checking these manually anyway and we don't want to miss the further steps just because one bit of data has changed. That's a business decision.
Also the config steps needed amendment.
NA
NA

circleci config amendment

---

scripts/sql_adhoc/cp1_audit/cp1_audit.sql

Steps needed to create CP1 audit files for sirius/casrec teams
Have to do process manually as there's not a place in pipeline to do it in the timeframes we need
NA

IN-1169 add cp1 audit scripts for go live

---

migration_steps/shared/validation_mapping.json
migration_steps/transform_casrec/transform/app/entities/invoice/finance_invoice.py

IN-1176
Left join Aged Debt onto invoices and set a confirmeddate where there's a match

IN-1176 Set invoices to Confirmed if they are present in Aged Debt

---

migration_steps/shared/validation_mapping.json

IN-1183 othernames - trim whitespace and convert to null

---

.circleci/config.yml
README.md
check_local_setup.sh
migrate.sh
migration_steps/initialise-dockerfile
migration_steps/initialise_environments/initialise_post_delete.sh
migration_steps/initialise_environments/initialise_pre_delete.sh
terraform/environment/tasks.toml

3hr hard limit is a little too close to comfort. 
I've tried playing around with chunking up the deletes. That is also promising but too risky imo at this stage. Safer to split out in my opinion.
NA

split out the initialise steps to avoid hard time limit

---

migration_steps/prepare_source_data/filter_data/app/sql/delete_filtered_source_data.sql

Validate automated letters against filtered casrec_letters
Add table to filtering script

IN-1090 Filter casrec_letters table

---

.circleci/config.yml
terraform/environment/cloud9.tf
terraform/environment/ecs_etl5_validate.tf
terraform/environment/ecs_etl_connectivity_check.tf
terraform/environment/variables.tf
terraform/shared/terraform.tfvars.json

Taking off safety features ready for live run
Change to real variables and uncomment the CI config.
NA

production run readiness

---

.circleci/config.yml

Update timeouts to handle longer deletion time on delete scripts
NA
NA

update the timeouts for task runnner

---

scripts/post_migration_fixes/pmf_reports_20220307_in1196/annual_report_logs.sql

update the annual report logs supervision_level

IN-1196 update the annual report logs supervision_level

---

scripts/post_migration_fixes/pmf_tasks_type_20220308_in1202/tasks.sql

update Task.type from ‘VICO’ to ‘VIRD’ WHERE casrec "Sup Desc" = 'URGENT VISIT REPORT'

IN-1202 PMR Task Type

---

.circleci/config.yml
.gitignore
migrate.sh
migration_steps/initialise_environments/delete_existing_data/app.py
migration_steps/initialise_environments/initialise_post_delete.sh
migration_steps/initialise_environments/initialise_pre_delete.sh

Check on migrations that the Sirius flag is set to Y on CP1 cases
Initially just tried to do this in the filter stage but that really made no sense so had to rejig some of our steps around. This now makes much more logical sense and allows us to check this before doing any deletions.
NA

IN-1194 add sirius migration flag check

---

scripts/post_migration_fixes/pmf_reports_20220310_in1178/annual_report_logs.sql

Part of IN-1178 - fixing report statuses
Any RECEIVED report with a lodged date is updated to LODGED

PM05 IN-1178 Update reports to LODGED

---

scripts/post_migration_fixes/pmf_reports_20220310_in1206/annual_report_logding_details.sql

IN-1206
Update lodgedstatus based on logic provided by Phil W

PM05 IN-1206 Update lodgedstatus

---

migration_steps/validation/post_migration_fixes/app/app.py
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/01_pmf_tasks_duedate_in1195/tasks.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/02_pmf_tasks_type_in1202/tasks.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/04_pmf_reports_in1196/annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/05_pmf_reports_in1197/annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/06_pmf_reports_in1178/annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/07_pmf_reports_in1206/annual_report_logding_details.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/08_pmf_sup_level_in1182/supervision_level_log.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/09_pmf_reports_in1204/annual_report_logs.sql
migration_steps/validation/validate_db/app/app.py

Work out which of the pmfs we need for phase 2
So looked through working out what all the post mig fixes did.. added purpose to them as thought it might be useful to see at first glance what they're doing as some of them weren't obvious.
Added vars for clientsource. Added latest pmfs.
NA

IN-1209 update post migration fixes

---

migration_steps/validation/post_migration_fixes.sh
migration_steps/validation/post_migration_fixes/app/app.py
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/10_pmf_reports_sw5578/annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/11_pmf_reports_in1198/annual_report_logs.sql
scripts/post_migration_fixes/pmf_report_reviewstatus_20220310_in1198/reports.sql
scripts/post_migration_fixes/post_migration_fixes.py

[IN-1198](https://opgtransform.atlassian.net/browse/IN-1198)
SQL, innit
n/a

IN-1198 Add script to update PENDING reports reviewstatus (PM11 integrated into automation)

---

migration_steps/shared/sql/transformation_functions.sql
migration_steps/transform_casrec/transform/app/utilities/standard_transformations.py

previously this only seemed to get 1.0s.. now it also gets 1s

IN-1232 update the convert_to_bool function

---

migration_steps/shared/sql/complex_functions.sql
migration_steps/transform_casrec/transform/app/entities/deputies/deputymapper.py
migration_steps/transform_casrec/transform/transform_tests/transform_data_tests/entities/deputies/test_deputy_mapper.py

IN-1237
Use first names and surname as the organisation name for organisations.

IN-1237 Update Organisation name mapping

---

migration_steps/validation/validate_db/app/sql/fixed_sql/deputy_addresses.sql

IN-1241 Limit deputy address validation to Phase2 only

---

migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/13_pmf_assignees_in1221/persons.sql

Fixed assignees as per latest matrix 
Bit complicated but this approach gave me a spreadsheet with matrix of all the data points to share with testers so they could sign it off.
NA

IN-1240 update to allocations requirements

---

migration_steps/prepare_source_data/counts_verification/sql/count_casrec_source.sql

IN-1241 amend to remove duplicates

---

migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/17_pmf_reports_in1243/annual_report_logs.sql

… where the interval between reportingstartdate and reportingenddate is greater than 365 days, adjust the start date to make it 365

IN-1243 PMF17 Set reporting start date to end date-365

---

migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/18_pmf_death_in1235/death.sql

Death status issue left over from lay that was subsequently fixed before phase 2 migration.
Simple swicheroo.
NA

IN-1235 pmf to fix death issue left over from lay

---

migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/19_pmf_reports_in1245/annual_report_logs.sql

Agreed would be better for audit purposes to fix forward with new pmf rather than back fix pmf5. 
Need to remove extra pending reports where they have 3 or more
NA

IN-1245 remove further duplicates

---

.circleci/config.yml
migration_steps/integration/business_rules/app/rules/finance_person_ids.py
migration_steps/prepare_source_data/counts_verification/sql/count_casrec_source.sql
migration_steps/shared/config.py
migration_steps/shared/validation_mapping.json
migration_steps/validation/post_migration_fixes/app/app.py
terraform/shared/terraform.tfvars.json

Further ticket to get green builds in preprod working.
NA
NA

IN-1253b extra bits to get it to work in pipeline

---

.circleci/config.yml
migrate.sh
migration_steps/prepare_source_data/counts_verification/sql/count_casrec_source.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/16_pmf_reports_in1239/01_annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/19_pmf_reports_in1245/annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/20_pmf_order_deputy_in1200/deputies.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/21_pmf_reports_in1251/annual_report_logs.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/22_pmf_order_deputy_in1201/order_deputy.sql
migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/25_pmf_order_deputy_in1250/order_deputy.sql

fix rehearsal and prod final jobs

---

.circleci/config.yml
migrate.sh
migration_steps/initialise_environments/delete_existing_data/app.py
migration_steps/initialise_environments/delete_existing_data/sql/deletion_preparation_statements.sql
migration_steps/initialise_environments/initialise_post_delete.sh
migration_steps/initialise_environments/initialise_pre_delete.sh
migration_steps/prepare_source_data/counts_verification/sql/count_cp1.sql
migration_steps/prepare_source_data/counts_verification/sql/count_non_cp1.sql
migration_steps/prepare_source_data/prepare_source_data.sh
terraform/environment/database.tf

Last ever PR on this project to stop us deleting allocations data.
Only delete P3 client data... A whole load of moving stuff around
NA

In 1270 Fix deletion from allocation team (and all non p3 clients)

---

.circleci/config.yml

circle fix
