- migration_steps/transform_casrec/tests/transformations/conftest.py
- migration_steps/transform_casrec/tests/transformations/transformations_from_mapping/test_perform_transformations.py
Made the tests use the same logger as everything else, so they work again
Also changed the test data to have 5 items so I don't have to mock the config (sometimes we take a random sample of data and the number of records is set in the config, default 5, the test only had 3 rows so it failed when it really shouldn't have)
Logger changes merged
Tests broke, sadness happened, oops
This is now sorted
> When I fixed the logs, I broke the tests

- migration_steps/shared/decorators.py
- migration_steps/transform_casrec/app/entities/clients/persons.py
- migration_steps/transform_casrec/app/transform_data/apply_datatypes.py
- migration_steps/transform_casrec/app/transform_data/transform.py
- migration_steps/transform_casrec/app/utilities/db_insert.py
Moved datatype stuff into `transform` as it seemed to be repeating a lot of stuff from there.
I've duplicated a couple of methods (the `_create_table_statement` and `_add_missing_columns`) so I could test it out on one table (client_persons) without affecting the others. Seems fine, so next PR will apply the same changes to the other tables and remove the `_with_datatypes` versions of those methods and the conditions.
Also added a generic timer decorator because I started to get worried that adding more to `transform` would slow things down (it doesn't... yet)
> IN-544 datatypes in transform step

- migration_steps/integration/load_to_staging/app/app.py
- migration_steps/integration/load_to_staging/app/clear_database.py
- migration_steps/integration/load_to_staging/app/move.py
- migration_steps/integration/load_to_staging/app/setup.py
- migration_steps/integration/load_to_staging/app/tables.json
Load the data from `integration` schema to `pre_migration` schema. 
This is kept out of the pipeline just like the other IN-590 PR, it results in a slightly different structure to the original version and will fall over before it gets to the end.
> IN-590 load to staging only

- migration_steps/integration/merge_with_target/app/merge_helpers.py
When calculating the `max_id` from Sirius, if there's no data it would return `None` which is not an int, so you can't add 1 to it to get the next id, and cause problems.
This fixes it 😃
> If no data in Sirius, return 0

- migration_steps/load_casrec/app/app.py
- migration_steps/prepare/prepare_target/app/app.py
- migration_steps/shared/db_helpers.py
Fix a race condition
Do all the setup of progress table prior to grabbing any of the ids. This way when we do the run each process is already allocated to a table. Edge case here is if a process dies then others won't pick up its processes but then again if it dies it fails the step function anyway so whatever. If I was designing something that could never fail ever I wouldn't do it like this but this is like 99.9% and thats good enough i think.
> fix an issue with race condition around updating progress table

- migration_steps/integration/integration.sh
- migration_steps/integration/merge_with_target/app/entities/cases/cases.py
- migration_steps/integration/merge_with_target/app/merge_helpers.py
- migration_steps/load_to_sirius/app/app.py
- migration_steps/load_to_sirius/app/reset_sequences.py
- migration_steps/shared/shared_tests/table_helpers/test_get_tables.py
- migration_steps/shared/table_helpers.py
- migration_steps/shared/tables.json
- migration_steps/transform_casrec/app/entities/cases/cases.py
- migration_steps/validation-dockerfile
- migration_steps/validation/post_migration_tests/app/app.py
- migration_steps/validation/post_migration_tests/app/checks/address_lines.py
- migration_steps/validation/post_migration_tests/app/checks/continuous_ids.py
- migration_steps/validation/post_migration_tests/app/checks/sequences.py
- migration_steps/validation/post_migration_tests/app/checks/uid_sequence.py
- migration_steps/validation/post_migration_tests/app/tables.json
- migration_steps/validation/post_migration_tests/app/utilities.py
- migration_steps/validation/post_migration_tests/post_mig_tests/conftest.py
- migration_steps/validation/post_migration_tests/post_mig_tests/sequences/test_sequences.py
- migration_steps/validation/requirements.txt
- migration_steps/validation/validate.sh
**Aim**
Get clients to work on the dev env
**What I did and why I did it:**
- added some post-migration tests 
Tacked on to the `validation` step. These check the stuff below - that the sequences have been reset as expected, and that the ids we inserted are continuous (this is not really important but I was confused about why our migrated data started with id 1000 when the max of the existing data was 82).
This includes a test for badly formatted address lines which is also not necessary, but I spotted it on dev and added it. This should be moved into the data validation soon, then this can be removed. I just got a bit overexcited at the time.
There's also some tests for the tests :D
- added functions to reset sequences
This was the major problem with dev. Remember those primary keys that …
> IN-599 - make client work on dev env

- terraform/s3.tf
Add S3 Bucket Policy to deny none SSL requests to the bucket to bring it in line with Security Hub recommendations.
Re-used proven policy from main Sirius Infra repo.
> SP-604 - Deny None SSL Requests to S3 Bucket

- .pre-commit-config.yaml
- migrate.sh
- migration_steps/integration-dockerfile
- migration_steps/integration/business_rules/app/app.py
- migration_steps/integration/business_rules/app/rules/global_uids.py
- migration_steps/integration/business_rules/app/utilities/clear_tables.py
- migration_steps/integration/business_rules/app/utilities/db_helpers.py
- migration_steps/integration/business_rules/app/utilities/generate_luhn_checksum.py
- migration_steps/integration/integration.sh
- migration_steps/integration/load_to_staging/app/move.py
- migration_steps/integration/reindex_ids/app/app.py
- migration_steps/integration/reindex_ids/app/existing_data/match_existing_data.py
- migration_steps/integration/reindex_ids/app/reindex/move_by_table.py
- migration_steps/integration/reindex_ids/app/reindex/reindex_foreign_keys.py
- migration_steps/integration/reindex_ids/app/reindex/reindex_primary_keys.py
- migration_steps/integration/reindex_ids/app/utilities/clear_database.py
- migration_steps/integration/reindex_ids/app/utilities/db_helpers.py
- migration_steps/load_to_sirius/app/move.py
- migration_steps/load_to_sirius/app/tables.json
- migration_steps/shared/table_helpers.py
- migration_steps/shared/tables.json
- migration_steps/transform_casrec/app/entities/cases/__init__.py
- migration_steps/transform_casrec/app/entities/cases/person_caseitem.py
- setup.cfg
So the way I was reindexing and calculating uids on `persons` (and other tables) was fine when there was only one entity writing to that table, but when more data was inserted later... well there were problems. Like the `id` calc started back at the beginning again so there were a load of duplicates. Same with uid.
Refactored `merge_with_target` into 2 new steps:
- `reindex_ids`
This... reindexes ids. There's also some placeholder for merging with existing data but nothing useful in there now.
Changed how this works to use the tables rather than entities, and to do as much work as possible in SQL rather than converting to a dataframe. It's simple stuff so no need for the df really.
- `business_rules`
Bit of a grand name for a step that currently just calculated some uids. This has also …
> IN-610 calculate uids better

- migration_steps/transform_casrec/app/data_tests/cases/cases_person_caseitem.py
- migration_steps/transform_casrec/app/data_tests/clients/cases_clients_addresses.py
- migration_steps/transform_casrec/app/data_tests/clients/cases_clients_persons.py
- migration_steps/transform_casrec/app/data_tests/clients/cases_clients_phonenumbers.py
- migration_steps/transform_casrec/app/data_tests/conftest.py
- migration_steps/transform_casrec/app/data_tests/deputies/cases_deputies_persons.py
- migration_steps/transform_casrec/app/data_tests/deputies/cases_deputy_phonenumbers_daytime.py
- migration_steps/transform_casrec/app/data_tests/deputies/cases_deputy_phonenumbers_evening.py
- migration_steps/transform_casrec/app/data_tests/test_complex_joins.py
- migration_steps/transform_casrec/app/data_tests/test_simple_joins.py
- migration_steps/transform_casrec/app/entities/deputies/__init__.py
- migration_steps/transform_casrec/app/entities/deputies/phonenumbers_daytime.py
- migration_steps/transform_casrec/app/entities/deputies/phonenumbers_evening.py
- migration_steps/transform_casrec/app/utilities/basic_data_table.py
Took this opportunity to sort out some of the data tests in `transform`. These are only useful when actually adding new entities to the step so do not run in the main pipeline. But still good to have them back.
No changes to any subsequent steps as phone numbers already reindexed etc from clients, so got all that for free.
> IN-608 deputy phonenumbers

- migration_steps/shared/mapping_definitions/lookups/deputy_status_lookup.json
- migration_steps/shared/mapping_definitions/lookups/discharge_lookup.json
- migration_steps/shared/mapping_definitions/order_deputy_mapping.json
- migration_steps/transform_casrec/app/data_tests/conftest.py
- migration_steps/transform_casrec/app/data_tests/deputies/cases_order_deputy.py
- migration_steps/transform_casrec/app/data_tests/test_conditional_lookup.py
- migration_steps/transform_casrec/app/data_tests/test_lookup_tables.py
- migration_steps/transform_casrec/app/entities/deputies/order_deputy.py
- migration_steps/transform_casrec/app/transform_data/conditional_lookups.py
* small mapping def changes (see [related pr](https://github.com/ministryofjustice/opg-data-casrec-migration-mappings/pull/22))
* changed `order_deputy` to use only the columns it actually needs (was previously using the whole `persons` table) and joined it up with the existing ids
* test for conditional lookups
* changed that typo for you @jamesrwarren
> In 625 order deputy extra bits

- migration_steps/shared/sql/drop_transformation_functions.sql
- migration_steps/shared/sql/transformation_functions.sql
- migration_steps/shared/validation_mapping.json
- migration_steps/validation/validate_db/app/app.py
Some entities need to be sorted using columns belonging to other mapping files
If you're sorting DISTINCT by a column, you need to display that column in the SELECT
If you're including the column, you need to format it correctly, inc. passing it through all lookup functions/data converstion etc - which means we actually need to import the full column mapping from another file
> In 651 Bonds validation and integrate secondary mapping files

- .circleci/config.yml
- .gitignore
- README.md
- casrec_data/run_ecs_task/Dockerfile
- casrec_data/run_ecs_task/run_ecs_task.py
- docker-compose.commands.yml
- docker-compose.override.yml
- docker-compose.yml
- migration_steps/load_s3-dockerfile
- migration_steps/load_s3/Dockerfile
- migration_steps/load_s3/synchronise_s3.py
- migration_steps/prepare-dockerfile
- migration_steps/prepare/case_details_to_s3/app/app.py
- migration_steps/prepare/prepare_target/app/app.py
- migration_steps/prepare/test_echo.sh
- migration_steps/requirements.txt
- run_ecs_task.sh
- terraform/casrec_tasks.toml
- terraform/template.tf
When we encounter issues in our data we want to be able to recreate them in our dev data so that we can debug locally.
We have an automated system to do this. It is a work in progress as the method to actually achieve
this is surprisingly complicated.
- Initialises terraform and runs a job that populates a template. This stops us needing to hard code the subnet values etc.
- Kicks off a container that runs an ECS task. We have added the script to do the anonymising and moving of date to s3
to the etl0 (prepare job) and this gets called with an override.
- ECS task pulls the relevant data, anonymises it, formats it and puts it in a folder in s3 ready for download.
- We then kick off the synchronise script using preproduction as the environment parameter. This downloads the data locally
and …
> IN-657 pull case data from preprod

- .circleci/config.yml
- docs/ci_scripts/run_step_function.py
- terraform/sirius_tasks.toml
Tidied up workflow a bit. Added approval for a full sirius elastic reindex to pre and qa. 
A few things to note...
- I would have done this for dev as well for consistency and testing purposes but the script actively prohibits that apparently.
- I put the approval BEFORE step function. Although we should only run it after the step function, I did this so that if step function fails for something totally stupid right at the end, then it shouldn't stop us running the reindex if we so need. However don't start kicking off reindexes whilst you're running the step function or you will have sad times.
Was trying to add way to kick off API task with Rich's env var but this is not really a good idea to do it from this side so canned that. Asked Andy if we can have the toggle flag as a param store …
> IN-699 add new sirius elasticsearch to our job

- .circleci/config.yml
- README.md
- docker-compose.override.ci.yml
- docs/ci_scripts/get_environment_entities.py
- migration_steps/shared/config.py
- migration_steps/transform_casrec/transform/app/app.py
- migration_steps/validation/api_test_data_s3_upload/app/app.py
- terraform/ecs.tf
- terraform/parameter_store.tf
Put entities as comma separate list (no spaces) in parameter store. Bring them in, convert to list and use them for preproduction, qa and prod environments.
Nothing too tricky here. Was just a bit of fun with some of the env vars in CI that needed some tweaking...
> IN-766 make entities selectable from parameter store

- migration_steps/shared/mapping_definitions/notes_mapping.json
- migration_steps/shared/validation_mapping.json
- migration_steps/validation/validate_db/app/app.py
Provides validation at a data(base) level for the migrated remarks entity
Same approach as the other entities: one SELECT statement picks the rows we are migrating from the casrec remarks table - another SELECT statement pics the corresponding rows from the target table (in this case, public.notes), and the two queries are compared using an EXCEPT statement which returns only the differences. These differences are then inserted into an 'exceptions' table for the entity, which we can refer back to later
Then, a second pass attempts to provide more context to the exceptions - testing each column in turn to try and identify which column/field failed - this is then saved alongside the failed row
This particular validation has highlighted a fair few inconsistencies with the remarks entity, …
> Remarks Casenotes DB validation

- migration_steps/transform_casrec/transform/app/utilities/db_insert.py
I was accidentally remapping the actual datatype in the mapping dict, which was fine locally because the total number of rows was less than the chunk size. 
However on preprod when it got to chunk 2 of `addresses.address_lines` (would have happened to any field that had the datatype remapped from something pandas-friendly to something sql-friendly, this was just the first one) then the datatype had been remapped from `dict` to `json` which makes no sense to Pandas, so it crashed.
> IN-775 preprod datatypes fix

- migrate.sh
- migration_steps/shared/config.py
- migration_steps/shared/helpers.py
- migration_steps/shared/validation_mapping.json
- migration_steps/validation/post_migration_tests/app/checks/address_lines.py
- migration_steps/validation/validate_db/app/app.py
- terraform/ecs.tf
So we had some failures on validating remarks on preprod. Main thing is just to turn off remarks for now.
Two issues were down to some data funny-ness
1) changed timestamp format as it was adding extra timestamp to the format for some reason
2) when no data for address lines it was expecting str
The last issue seemed to be that it was taking a bajillion years to run against remarks. Split out the SQL queries so we commit after each one. Slightly slower but means we shouldn't run out of memory when hitting big queries and we can see which query it fails on when it does fail. Overall I think this is worthwhile. We still keep the all in one file in case we want to run the full thing in one go.
Finally fixed a couple of typos and turned off remarks.
NA
> IN-780 fix validation bug

- migration_steps/shared/mapping_definitions/client_nodebtchase_warnings_mapping.json
- migration_steps/shared/mapping_definitions/client_saarcheck_warnings_mapping.json
- migration_steps/shared/mapping_definitions/client_special_warnings_mapping.json
- migration_steps/shared/mapping_definitions/client_violent_warnings_mapping.json
- migration_steps/shared/mapping_definitions/deputy_special_warnings_mapping.json
- migration_steps/shared/mapping_definitions/deputy_violent_warnings_mapping.json
- migration_steps/shared/validation_mapping.json
The answer to this was not to exclude closed_by from validation but to mark the whole field in the mapping file as is_complete = false, as it is marked as unmapped in the spreadsheet.
I've made the changes in this repo and when the mapping files are next regenerated they should be the same.
> IN-768 mark closed_by as unmapped as per spreadsheet

- migration_steps/shared/config.py
- migration_steps/shared/quick_validation/dev_row_counts.json
- migration_steps/transform_casrec/transform/app/entities/crec/persons.py
- migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_logs.py
- migration_steps/transform_casrec/transform/app/entities/warnings/client_person_warning.py
- migration_steps/transform_casrec/transform/app/entities/warnings/deputy_person_warning.py
- migration_steps/transform_casrec/transform/app/transform_data/apply_conditions.py
1. reporting gave a datatype error because `client_id` was null and an int cannot be null
- changed to an inner join so I'm not migrating any reporting records that do not have a `client_id`
- also added the `reapply_datatypes_to_fk_cols` to make sure `client_id` is an int
2. same issue with crec
- same fix as above
3. persons_warning once again a problem, because this team has no warning records
- put in a check to see if the `warnings` table is empty and if so, bypass the data and just create the empty table 
4. snuck in a cheeky entity check to kill it if no entities are enabled (IN-747)
> IN-795 team 2 errors

- migration_steps/validation/validate_db/app/app.py
IN-784 investigate and fix 3 exceptions on client_persons.clientaccommodation
The following three values in accommodation_type_lookup return an empty string:
RCH
RH
LAH
This is being migrated as NULL in Sirius. 
'' !== NULL, but this is no doubt the desired behaviour, so validation has been adjusted to pass
> IN-784 convert empty string to NULL even if from lookup

- migration_steps/transform_casrec/transform/app/transform_data/apply_datatypes.py
Pandas is picky about dates, it will not let me convert anything before 1677 and after 2262.
Yeh it's probably true that any dates outside that range are wrong, but our policy of non-interference means we don't want to be going around 'correcting' Casrec data so we want to migrate it anyway. Leave pandas to its own devices and it will put NaT in there instead which is even wronger.
> IN-798 ignore pandas date errors

- migration_steps/shared/mapping_definitions/deputy_persons_mapping.json
- migration_steps/transform_casrec/transform/app/transform_data/apply_datatypes.py
- migration_steps/transform_casrec/transform/app/transform_data/lookup_tables.py
The problem was due to Pandas - when you convert a column to a boolean it converts all null values to false. But sometimes we want null, so I have to tell it that explicitly.
Mapping changes are from the [matching PR here](https://github.com/ministryofjustice/opg-data-casrec-migration-mappings/pull/57).
> IN-783 bonds validation errors

- migration_steps/integration/business_rules/app/app.py
- migration_steps/integration/load_to_staging/app/app.py
- migration_steps/integration/reindex_ids/app/app.py
- migration_steps/shared/config.py
- migration_steps/transform_casrec/additional_data/app/app.py
- migration_steps/transform_casrec/transform/app/app.py
Added a little feature flag mechanism to `config`. Used the same format as the `enabled_entities` so if we want to use param store for the 'real' data we can use the same pattern easily enough. 
Added `additional_data` in there too as that was sort of hacked in as an entity, this is better.
~Currently it's ON for preprod, because I have a data issue to debug so can't turn it off~
No longer true. I turned it OFF for preprod so I don't have to speed-fix the data issue before tonight's run.
~Literally followed [GitHub's markdown instructions](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to do a strikethrough above and it didn't work 😞~
Figured out how to do a strikethrough
> IN-804 added feature flag

- migration_steps/shared/validation_mapping.json
- migration_steps/validation/validate_db/app/app.py
Over the past few weeks a few validation exceptions have crept in centred around comparison of dates - probably as new fields have been enabled. 
Compare dates like-for-like whilst still retaining and saving original casrec text formatting (transform the Sirius side, not the Casrec side)
As part of this, Validation has seen some refactors in the interest of clarity esp regarding naming
> In 809 dates and refactor

- migration_steps/shared/validation_mapping.json
Validation for deputy phone numbers. Protects the following mappings:
casrec_csv.deputy."Contact Telephone" => sirius.phonenumbers (type = work)
casrec_csv.deputy."Contact Tele2" => sirius.phonenumbers (type = Home)
casrec_csv.deputy."Mobile" => sirius.persons.mobilenumber
NOTE: contact_tele3 and Mobile2 don't seem to be migrating
Usual data validation process
> IN-743 validation protection for Deputy phonenumbers

- migration_steps/transform_casrec/transform/app/transform_data/transform.py
Ah the old python 'not a copy' problem, you'd think I'd have learnt by now.
So once a condition has been applied I was removing that entry from the conditions dict, but because python is python, I was actually removing it from the original `table_definitions` dictionary, meaning in the second pass of the chunking the `source_conditions` key was empty.
Now, instead of using the original conditions dict, I am giving it a new dict, so when I pop stuff it only affects the new one, not the original `table_definitions` dictionary.
> IN-860 duplicate warnings being migrated

- migration_steps/shared/tables.json
- migration_steps/validation/api_tests/functional_tests/app.py
Turns out when you add a warning, crec or order it automatically adds a note to the supervision_notes table, so we need to reset the table sequences and the supervision_note table sequence.
Not sure what would happen if you turn the notes entity off, but as that work is now finalised that's unlikely to happen so we'll deal with that if we have to.
> IN-859 & IN-874 warning, order & crec functional tests fail

- migration_steps/shared/validation_mapping.json
- migration_steps/validation/validate_db/app/app.py
- migration_steps/validation/validate_db/app/fixed_sql/crec_persons.sql
DB Validation for Crec
Same process as with other validation - EXCEPT the SQL necessary to pull only the latest status for each client proved too complex to be generated dynamically so the necessary sql is saved to a static file.
The validation app.py now checks a directory to see if a pre-saved static SQL file is present for the entity and uses it, if present.
> IN-787 Crec DB validation

- migration_steps/shared/validation_mapping.json
The warning text and warning type set in Sirius had changed in IN-785: 3 types of warnings not migratingPM TESTING, have updated the validation to check for the new text patterns
> IN-726 update warnings WHERE text in response to changes made in IN-785

- migration_steps/prepare/create_skeleton_data/app/skeleton_data.py
FinancePerson entities do not need migrating because a large number have already been imported in Sirius live (245k), and the rest will be imported by the Finance team prior to data migration.
Ensure that each client on localdev has a FinancePerson entity with a unique finance_billing_reference (aka SOP number)
Insert into finance_person table as part of setting up skeleton data on localdev
-
> Create FinancePerson entities on localdev

- terraform/cloud9.tf
Don't create cloud9 env for preqa
> dont create cloud9 for preqa

- migration_steps/transform_casrec/transform/app/utilities/convert_json_to_mappings.py
Transformations should reference the column alias instead of the original column name. In most cases they are the same, except when the transformation is on a copied column e.g. "SomeCol 1", "SomeCol 2" etc
> Use column alias instead of original column name

- migration_steps/load_to_sirius/move_data/insert_data.py
- migration_steps/transform_casrec/transform/app/utilities/db_insert.py
- migration_steps/validation/post_migration_tests/app/checks/continuous_ids.py
3 parts to the problem:
1. _transform_ was not adding the `casrec_details` column to an empty table, which is needed later
2. _load_to_sirius_ insert crashed when it found an empty table (because of the refactoring I did a couple of weeks ago)
3. _post_migration_tests_ claimed `death_notifictations` had failed when in reality nothing had changed
> Fix problems with death in team 2

- migration_steps/shared/config.py
- terraform/parameter_store.tf
Internally translates to empty string (AWS Param store doesn't like empty values)
Translates AWS value of "0"|"all"|"All"|"ALL" to an empty string, internally
Filtering then works as normal (is disabled)
> Lay team filtering disabled if AWS param '0'|"all"|"All"|"ALL"

- .circleci/config.yml
- README.md
- docker-compose.commands.yml
- migrate_tagged_version.sh
- scripts/migrate_tagged_version/Dockerfile
- scripts/migrate_tagged_version/app.py
- terraform/secrets.tf
We want to be able to kick off specific version to different environments easily. We have so far used circle and it's a bit lacking in the dropdowns needed to do this through the GUI.
As such we need a script that makes it easy for any dev to deploy specific versions.
Put together a hodge-podge of python and shell scripts to create a beautiful monster that's easy to run. 
Looks a bit like this when you run it:
Nothing in particular but there were some fiddly bits...
> IN-902 create kick off job functionality

- migration_steps/load_casrec/app/app.py
- migration_steps/shared/custom_errors.py
- migration_steps/shared/validation_mapping.json
- migration_steps/transform_casrec/transform/app/entities/warnings/client_nodebtchase_warnings.py
- migration_steps/transform_casrec/transform/app/entities/warnings/client_saarcheck_warnings.py
- migration_steps/transform_casrec/transform/app/entities/warnings/client_special_warnings.py
- migration_steps/transform_casrec/transform/app/entities/warnings/client_violent_warnings.py
- migration_steps/transform_casrec/transform/app/entities/warnings/deputy_person_warning.py
- migration_steps/transform_casrec/transform/app/entities/warnings/deputy_special_warnings.py
- migration_steps/transform_casrec/transform/app/entities/warnings/deputy_violent_warnings.py
- migration_steps/transform_casrec/transform/app/transform_data/apply_conditions.py
- migration_steps/transform_casrec/transform/app/transform_data/transform.py
All warnings are migrated and validated correctly.
Update validation query for deputy_violent_warnings to use the expected warning type i.e. 'REM - Violence Warnings'
Ensure that chunking is not interrupted by an EmptyDataFrame exception raised after applying conditions.
> IN-992 Fix transformations and validations for warnings

- migration_steps/load_casrec/app/app.py
Handles the 'NaT' on Bond Discharge date field which is an artefact of converting Excel files with pandas
Added another row to the tumour of exceptions which is metastasising nicely at the heart of our code
We're going to be replacing the excel > pandas route with a copy of csv directly into postgres soon, so we'll be able to nuke it soon enough
> Add Bond Discharge column to horrific nauseating antipattern

- migration_steps/shared/validation_mapping.json
- migration_steps/validation/api_test_data_s3_upload/app/validation/csvs/invoice.csv
- migration_steps/validation/validate_db/app/app.py
- scripts/api_tests_generator/app.py
Validate that blank phone numbers are not being migrated across.
Enable validations for "deputy_daytime_phonenumbers" and "deputy_evening_phonenumbers".
Add a where clause to the casrec side of the validation in order to exclude blank phone numbers.
> IN-933 Enable/fix phone number validations

- migration_steps/validation/validate_db/app/sql/fixed_sql/crec_persons.sql
Crec mapping now uses "at" column instead of "at.1"
Update DB validation accordingly
> IN-957 Update crec validation

- scripts/finance/payments/1. get_last_ledger_and_allocation_ids.sql
- scripts/finance/payments/2. import_payments.sql
- scripts/finance/payments/3. batch_payments.sql
- scripts/finance/payments/4. validations.sql
- scripts/finance/payments/5. cleanup.sql
Payments differ from all other entities in that they will be imported manually via Sirius front-end after data migration has ran.
We need a way of batching all imported payments together, and report on the number of migrated/batched ledger entries and allocations per calendar day.
Not sure of the best place to put these scripts because they will be executed manually after data migration:
1. Store the last ledger entry and allocation IDs in a temporary table prior to importing payments.
2. Import payments (manual process)
3. Create a new batch number in Sirius DB and set it on all newly created ledger entries and allocations.
4. Report on number of newly created ledger entries and allocations, grouped by batch number, to ensure that everything has been batched and the correct number of …
> IN-868 Payments batching and validation

- migration_steps/validation/api_test_data_s3_upload/app/validation/csvs/deputy_fee_payer.csv
- migration_steps/validation/api_tests/shared/api_test.py
- scripts/api_tests_generator/app.py
- scripts/api_tests_generator/deputy_fee_payer.csv
Add API tests for Deputy Fee Payer
Check that /api/v1/orders/{id1}/deputies/{id2} endpoint returns correct Deputy Fee Payer flag
> IN-887 API tests for Deputy Fee Payer

- migration_steps/shared/tables.json
Prevent duplicate primary key constraint errors when recording death notifications post-migration.
Reset the ID sequence
> IN-866 Reset death_notifications ID sequence

- migration_steps/validation/validate_db/app/app.py
This column has grown increasingly unfit for purpose with the addition of recent more filtered entities, and is now downright confusing. It would be better to be removed completely
More changes are coming to the validation report to strip out other unnecessary metrics
> Remove validation attempted column

- migration_steps/validation/validate_db/app/app.py
I don't know how this wasn't picked up until tasks, but we use default value in validation in cases where lookup is null.
Mustn't affect any other entities.
Fixed.
> Ensure default value is used in cases where lookup is null

- migration_steps/load_to_sirius/move_data/utilities.py
- migration_steps/prepare/create_skeleton_data/app/skeleton_data.py
Prevent finance_person_id from being converted to float when loading invoices, ledger entries and fee reductions to Sirius.
Add finance_invoice, finance_ledger and finance_remission_exemption to the list of special cases where certain columns need casting to a certain type - in this case finance_person_id to Int64
Remove the finance_person record from one of the persons on local/dev to ensure adequate test coverage
> Prevent finance_person_id from being converted to float

- migration_steps/prepare/create_skeleton_data/app/skeleton_data.py
- migration_steps/shared/custom_logger.py
Ensure that the console log output on local includes any `extra` data that was passed in to the logger.
Before:
After:
Loop over extra data params for each log message and add them to the format string.
> Improve local log output

- migration_steps/validation/validate_db/app/sql/fixed_sql/annual_report_logs.sql
[IN-996](https://opgtransform.atlassian.net/browse/IN-996)
Simple removal of SQL clause which validates migration of Review Date field, which is no longer validated.
n/a
> IN-996 Remove validation of annual_report_logs field which is not mapped

- migration_steps/shared/validation_mapping.json
The fields were actually empty strings, not null, so the previous change wasn't working as intended.
> IN-1007 Use default description on client note when empty not null

- migration_steps/validation/validate_db/app/app.py
- migration_steps/validation/validate_db/app/sql/fixed_sql/deputy_feepayer_id.sql
Fix validation errors - 2 on local and 4 in pre.
Update the validation SQL to exclude Open orders.
The conditional to exclude Open orders was applied recently to cases, which then broke this validation.
Exiting on validation failure in local/dev will catch these errors and make them easier to fix.
> IN-995 Fix deputy_feepayer validation errors

- .circleci/config.yml
- terraform/environment/sirius_tasks.toml
Use the new elastic reset (and change a couple of other pipeline bits...)
Switching elastic is a simple switch of the name (did a test in dev to check it works)
Now that we have a preprod that should consistently work, I've decided to just get rid of the nightly preqa and have it kick off from the back of preprod. Really it was only supposed to be a temp workaround to other issues that we had it running separately. Got rid of the load casrec bit from pre as tbh it's not picking up s3 changes currently and we have it running in dev every run that checks the functionality isn't broken. So really it's just an extra step we can remove for now.
Added an extended timeout for api tests.
NA
> IN-1028 add new elastic reset

- migration_steps/load_to_sirius/post_migration_db_tasks/finance_batch_numbers.py
- migration_steps/validation/api_test_data_s3_upload/app/validation/api_test_csvs/deputy_notes.csv
- scripts/api_tests_generator/preprod_cases/visits.csv
Fix batch number update taking a very long time..
Also to save a PR, update with some API fixes we've seen based on sorting out API tests.
Looked at QEP for the query to update batch numbers and saw it was doing scans and ignoring the index on persons table. This is often due to bad statistics meaning it makes bad decisions..  Like it believes the table is small enough that scan would be more efficient. We can trick it by telling it that seeks are way cheaper and then it uses the index correctly and takes like 3 seconds instead of an hour and half to update... (tested in preprod)
How to look at QEPs in postgres.
> IN-1033 make batch number updates faster

- migration_steps/load_casrec_schema/app/app.py
- migration_steps/prepare/create_stage_schema/app/app.py
- migration_steps/shared/db_helpers.py
- migration_steps/validation/validate_db/app/app.py
Fixes the last remaining client_notes validation error, but more importantly fixes some dodgy string replacements
Rename the schema name prior to exporting it, so that we won't have to rename it with find&replace in the SQL dump file.
Other string replacements (like the SQL user/owner) were made a lot more specific using regex.
> IN-1032 Fix client_notes validation error

- migration_steps/shared/validation_mapping.json
Improvement to validation. The migration was fine but the validation showed 1 row discrepancy
NULL warningtext isn't caught by the IN() statement, so adjust the where clause
> IN-1009 validation tweak to allow for null warningtext

- migration_steps/shared/validation_mapping.json
- migration_steps/validation/validate_db/app/app.py
- migration_steps/validation/validate_db/app/sql/fixed_sql/finance_person_ids.sql
IN-1048
Check for NULL finance_person_id in all migrated finance entities and add to exceptions table
> IN-1048 Custom DB validation to check that finance_person_id is set on all migrated records

- migration_steps/integration/copy_from_sirius/app/utilities/copy_tables.py
- migration_steps/prepare/create_skeleton_data/app/lookups/dev_data_fixes.py
- migration_steps/prepare/create_skeleton_data/app/skeleton_data.py
- migration_steps/prepare/delete_existing_data/sql/delete_statements.sql
- migration_steps/shared/tables_to_copy_from_sirius.json
Fix for IN-1058 - Tasks not showing in Sirius Dashboard.
The tasks in question were "case tasks" i.e. linked to a specific case rather than a person. The cases were (rightly) deleted by our deletion script as they weren't Pilot One, which then left the tasks not linked to anything, hence causing an error on the front-end.
Delete case tasks that are not linked to a Pilot One case.
Also allocate all users on dev to a team (team ID 100), so that we can see all migrated taks on the Dashboard locally by selecting "My team's tasks" in the filter
> IN-1058 Delete tasks not linked to a Pilot One case

- migration_steps/shared/validation_mapping.json
Fix client_nodebtchase_warnings validation.
Set explicit condition for "Debt chase" = 1 to capture any errors in future in case more values get added in Casrec
> Fix client_nodebtchase_warnings validation.

- migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_type_assignments.py
- migration_steps/transform_casrec/transform/transform_tests/transform_data_tests/entities/reporting/test_annual_report_type_assignments.py
[IN-1100](https://opgtransform.atlassian.net/browse/IN-1100)
Fix bug in my code which assigned reporttype using incorrect casrec order.
If there are two rows like so in a dataframe:
```
| 0 |                 1 | 2001-01-26 00:00:00 |                           10000037 | Closed     |              2 |               10000037 |
| 1 |                 1 | 2001-01-26 00:00:00 |                           10000037 | Active     |              2 |               10000037 |
```
...and you use idxmax() to get the ID of the row with the largest date value (third column here), you get the first row containing the largest value (row 0), not the second row (row 1).
> IN-1100 reporttype assignment

- migration_steps/prepare_source_data/counts_verification/pre_migration_counts.py
- migration_steps/prepare_source_data/counts_verification/sql/count_casrec_source.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_existing_cp1.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_non_cp1.sql
- migration_steps/validation/counts_verification/count_final.py
- migration_steps/validation/counts_verification/sql/count_final.sql
Do a quick count of each entity post delete-script. Allows us to quickly rule-out (or rule in) the delete script when investigating count discrepancies
The counts are taken after the delete script has run. Expected values are zero, except for clients which are not deleted
> In 1066 non cp1 counts

- migration_steps/shared/validation_mapping.json
Incorrect linking meant that unexpected tasks were getting through.
This SQL may be superseded soon with a move to strip linking to cases altogether, or it might not. 
> IN-1133 fix SQL linking sup_activity to orders in casrec

- .circleci/config.yml
- base_image/requirements.txt
- docker-compose.override.yml
- docker-compose.yml
- migration_steps/shared/shared_tests/requirements.txt
- migration_steps/unit-tests-dockerfile
- migration_steps/unit-tests.sh
Dependabot flow was still janky and we don't need to be pushing images here as it gets done after merge. This makes it smooth sailing.
Also moved the tests into containers as that seemed more secure than installing dependencies directly onto circle which has numerous env vars
> IN-1130b cut down dependabot flow further

- .circleci/config.yml
- docker-compose.sirius.yml
- migration_steps/load_to_sirius/move_data/utilities.py
I've smooshed together 4 little bug fixes here for simplicity in getting it through CI.
They are:
- This mornings fail on preprod is because of pandas doing that annpoying thing with int conversion so fixing deputycasrecid as int64 on load.
- tag of prod image never worked so made that dynamic
- I'd broken push mappings that happens only on merge of pr when i containerised all the unit tests. Adding the dependencies just for that back in.
- unittests needs to be in the sirius docker-compose file as it's in the override file
> fix deputycol as int64 and minor ci improvement

- migration_steps/prepare_source_data/counts_verification/sql/count_casrec_source.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_cp1.sql
Address counts were further complicated by surname sometimes being an org or sometimes a surname and the fact that some of the previous cp1 postcodes shared the same deputy details and postcodes as new ones. 
This is a limitation of different way they are linked so we can't accurately infer the counts from the casrec data.. or at least i couldn't
> IN-1135 fix address count

- migration_steps/validation/api_test_data_s3_upload/app/validation/api_tests/deputy_clients.csv
- migration_steps/validation/api_tests/shared/api_test.py
Just a quick one to improve two things I noticed when fixing the files for filtered api tests
1. It's not logging when we're filtering out a tested case
2. We have no mechanism to just check if something is in a result set. We often do want to check the full result set but sometimes where it changes a lot and we're only interested if a code appears in the list then we need a check that doesn't check all the responses but just that a certain field appears in the result set brought back.
Made the above changes
NA
> IN-1147 improve filtered api tests

- scripts/log_parser/log_parser.py
The log parser allows you to select logs from a single log group between certain datetimes and see which
are the worst performing areas of the sequential process.
This is useful for sequential runs like this migration as we're simply interested in the time difference
between log messages.
This should give us a good indication of where the process is taking a long time.
So this was a bit of L&D fun I guess but it's quite useful and saves looking through logs which is painful. The results have proven very useful and give me place to start looking for efficiencies.
NA
> add log parser to find worst performing areas

- migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_logs_pending.py
- migration_steps/validation/api_test_data_s3_upload/app/validation/api_tests/reports.csv
- migration_steps/validation/validate_db/app/sql/fixed_sql/annual_report_logs.sql
[IN-1160](https://opgtransform.atlassian.net/browse/IN-1160)
reviewdate was missing for PENDING reports, so set to NO_REVIEW as a default.
n/a
> IN-1160 Fix bug where PENDING reporting period dates cannot be edited 

- migration_steps/prepare_source_data/counts_verification/sql/count_cp1.sql
- migration_steps/shared/validation_mapping.json
- migration_steps/validation/validate_db/app/sql/fixed_sql/scheduled_events_reporting.sql
- terraform/shared/terraform.tfvars.json
Removed the updateddate from validation as we know it works and if we ever do anything on separate days then it puts all our validation out which could lead to a lot of stress on the migration day.
Also was looking at worst performing areas and got this query down from 25 mins to a few seconds. The next worst is also a json query but no matter what i tried I couldn't get it to use the indexes.
NA
NA
> IN-1155 remove updateddate from validation

- migration_steps/shared/validation_mapping.json
- migration_steps/transform_casrec/transform/app/entities/deputies/order_deputy.py
- migration_steps/validation/validate_db/app/app.py
We had a problem that the overall deputy status was being applied to the deputyship (in Sirius data terms, the row in the order_deputy table).
This is ok in most cases, except where casrec_csv.deputyhip.joint = '5' - in which case we need to override the deputyship data as follows:
(Sirius)
order_deputy.statusoncase = 'CLOSED'
order_deputy.statusoncaseoverride = 'DISCHARGED'
After discussion with Elliot, a transform seemed like overkill - Added a couple of tiny helper functions to do the conditional dataframe field change.
When I came to add test coverage - I discovered that the order_deputy table wasn't covered by automated db validation, so added this in.
Pandas is simple when you know how.
> In 1163 orderdeputy status

- migration_steps/prepare_source_data/counts_verification/sql/calculate_result.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_casrec_source.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_cp1.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_non_cp1.sql
- migration_steps/prepare_source_data/counts_verification/sql/count_non_supervision.sql
- migration_steps/prepare_source_data/counts_verification/sql/schema_up.sql
Events is too slow to bring back. Also we can't properly audit it because it's so huge and takes too long. 
Wanted to check our document counts to make sure we're correctly moving the documents.
Added a couple of statuses of 'DELETE - OK' where i wanted to check that delete hadn't gone wrong but it was too hard to work out the figure for the expected after migrate (already covered in validation for one and linking id for the other)
Did some very long and laborious setup locally go get the logic right for the document stuff... was very boring
> IN-1135c more delete count validation

- migration_steps/prepare_source_data/load_casrec_fixtures/app/account_fixtures.py
- migration_steps/transform_casrec/transform/transform_tests/transform_data_tests/table_transforms/test_table_transforms_annual_report_logs.py
Defaults to raise as behaviour for non business days. Make it default to forward everywhere. Only applies when it's not a business day.
Changed now() to be a weekend day to recreate error then changed option to forward and tested migrate.sh.
NA
> IN-1185 fix weekend breakages

- scripts/post_migration_fixes/pmf_reports_20220308_in1197/annual_report_logs.sql
IN-1197
Delete the second Pending report and create a scheduled event for the remaining Pending report.
> PM05 IN-1197 Fix for cases having multiple Pending reports

- scripts/post_migration_fixes/pmf_sup_level_20220308_in1182/supervision_level_log.sql
Initially we only migrated the latest supervision levels.
The purpose of this is to bring accross all suppervision level changes, as they are required for billing purposes.
Delete all supervision level logs that were migrated initially, as they have an incorrect appliesfrom date.
Order risk assessments chronologically (by "Start Date") for each case and filter out any that didn't change the supervision level. Where two or more risk assessments have the same "Start Date", we use the one with the latest "Date Create" date.
There is 1 risk assessment in the DB that doesn't have a "Date Create", so we default that to "Start Date".
> PM08 IN-1182 Migrate supervision level logs from casrec_csv.risk_assessment

- scripts/post_migration_fixes/09_pmf_reports_20220311_in1204/annual_report_logs.sql
IN-1204
For each annual report, find the latest supervision level that was in effect on or before the reportingperiodenddate and set it as the casesupervisionlevel of the annual report.
Lateral joins are awesome
> PM09 IN-1204 Set casesupervisionlevel on migrated annual_report_logs

- migration_steps/shared/sql/transformation_functions.sql
- migration_steps/transform_casrec/transform/app/entities/reporting/__init__.py
- migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_logs.py
- migration_steps/transform_casrec/transform/app/entities/reporting/annual_report_logs_pending.py
- migration_steps/transform_casrec/transform/app/entities/reporting/duedatecalculator.py
- migration_steps/transform_casrec/transform/app/utilities/standard_transformations.py
- migration_steps/transform_casrec/transform/transform_tests/transform_data_tests/entities/reporting/test_duedatecalculator.py
- migration_steps/transform_casrec/transform/transform_tests/transform_data_tests/table_transforms/test_table_transforms_annual_report_logs.py
- migration_steps/validation/validate_db/app/sql/fixed_sql/annual_report_logs.sql
[IN-1208](https://opgtransform.atlassian.net/browse/IN-1208)
* Remove linear mapping to reportingduedate
* Add conditional mapping based on presence of active PA/PRO deputies (21 calendar days for Lay, 40 working days for PA/PRO)
* Fix validation 
n/a
> IN-1208 PA/PRO reportingduedate

- migration_steps/shared/sql/complex_functions.sql
- migration_steps/shared/validation_mapping.json
- migration_steps/transform_casrec/transform/app/entities/deputies/deputymapper.py
- migration_steps/transform_casrec/transform/app/entities/deputies/persons.py
- migration_steps/transform_casrec/transform/transform_tests/transform_data_tests/entities/deputies/test_deputy_mapper.py
[IN-1119](https://opgtransform.atlassian.net/browse/IN-1119)
Set deputysubtype based on the deputy code and presence of surname. Then set organisationname and clear other name fields for organisations.
n/a
> IN-1119 PA/PRO deputies set persons.deputysubtype

- migration_steps/integration/business_rules/app/rules/client_statuses.py
- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/13_pmf_assignees_in1221/persons.sql
Somehow had the ordering of death notified and death confirmed the wrong way round.  Also think that inner join for assignees is a bit too restrictive and would stop pro assignees that have a deputy owner entry from getting updated.
NA
NA
> IN-1219 fix ordering of death statuses

- .circleci/config.yml
- migration_steps/validation/post_migration_fixes/app/app.py
- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/08_pmf_sup_level_in1182/supervision_level_log.sql
Rollbacks were added where validation mismatched but this is actually super unhelpful as all the validation mismatches are out by a few cases and it's hard to work out what they are and it's holding up testing. Better to remove the rollbacks and then look into validation issue and let UAT get on with testing.
Removed rollbacks
Removed a bit of Dimitars script that he said was now not needed.
> IN-1234 get rid of unneeded rollbacks for pmfs

- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/15_pmf_tasks_in1244/tasks.sql
This was already manually run in prod on 11/04/22 at about 9:45am as part of a P1 update
Update tasks.caseownertask and tasks.assignee_id on tasks with an assignee of Migration User
Used standardised PMF script approach
> IN-1244 PMF15 tasks update caseownertask

- migration_steps/validation/post_migration_fixes/app/app.py
- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/14_pmf_reports_in1242/annual_report_logs.sql
Users were adding further info dates for which rcvd dates were expected. In some cases though instead of adding received date, they just added it in the review date column
Where there is a further date with no matching rcvd date and the review date has been set then add the review date as resubmit date.
Tried with the 'sirius' type logic first but it was bringing back mostly rows for which there was no further date at all. As such we have had to do a join with the original data to get the correct info.
NA
> IN-1242 pmf for annual report logs resubmit date

- .circleci/config.yml
- migrate.sh
- migration_steps/transform_casrec/transform/app/entities/timeline/timeline_event.py
- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/24_pmf_reports_in1267/annual_report_logs.sql
- terraform/environment/tasks.toml
There are a number of reports in casrec that are on the cases before any orders were made. This is due to a casrec decision from years ago but is confusing now that they're being moved to sirius and the data shouldn't be there. 
PMF to remove it
NA
> IN-1267 remove reports predating orders p3

- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/18_pmf_order_deputy_in1250/01_insert_missing_order_deputy.sql
Some hybrid cases where missing an order_deputy for both active orders. This script identifies the missing order_deputys and copies the deputy info over from the ‘other’ case
Kept the logic as-is from Jim's SQL script except:
* Save the 'dual order' (hybrid) cases as a table, in case we need to audit later
* Save the 'missing_orders' cases as a table, instead of an ephemeral 'WITH' subclause
* renamed quite a bit to make logic clearer (to me at least) the split between hw and pfa instead of using numbers
* order_deputy_ids were being confusingly named order_ids... fixed those
`create schema pmf_blah;
-- The setup SQL
with dualOrders as (
select p.id as p_id, c1.id as c1_id, c2.id as c2_id
from persons p …
> IN-1250 PM18 add missing order_deps

- migration_steps/validation/post_migration_fixes/app/pmf_sql_statements/25_pmf_address_in1272/address.sql
Fix airmailrequired flag, which was not set on migration 1 for deputies and client addresses which are overseas. (problem not found in Phases 2 & 3)
Standard PMF approach
> In 1272 PMF25 fix airmailrequired flag
